// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.

// PROGRAM		"Quartus II 64-Bit"
// VERSION		"Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition"
// CREATED		"Tue Mar 07 00:52:02 2017"

module \4by16Mux (
	I0,
	I1,
	I2,
	I3,
	S,
	F
);


input wire	[15:0] I0;
input wire	[15:0] I1;
input wire	[15:0] I2;
input wire	[15:0] I3;
input wire	[1:0] S;
output wire	[15:0] F;

wire	[15:0] F_ALTERA_SYNTHESIZED;
wire	SYNTHESIZED_WIRE_128;
wire	SYNTHESIZED_WIRE_129;
wire	SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	SYNTHESIZED_WIRE_4;
wire	SYNTHESIZED_WIRE_5;
wire	SYNTHESIZED_WIRE_130;
wire	SYNTHESIZED_WIRE_131;
wire	SYNTHESIZED_WIRE_10;
wire	SYNTHESIZED_WIRE_11;
wire	SYNTHESIZED_WIRE_12;
wire	SYNTHESIZED_WIRE_13;
wire	SYNTHESIZED_WIRE_18;
wire	SYNTHESIZED_WIRE_19;
wire	SYNTHESIZED_WIRE_20;
wire	SYNTHESIZED_WIRE_21;
wire	SYNTHESIZED_WIRE_26;
wire	SYNTHESIZED_WIRE_27;
wire	SYNTHESIZED_WIRE_28;
wire	SYNTHESIZED_WIRE_29;
wire	SYNTHESIZED_WIRE_35;
wire	SYNTHESIZED_WIRE_36;
wire	SYNTHESIZED_WIRE_37;
wire	SYNTHESIZED_WIRE_38;
wire	SYNTHESIZED_WIRE_43;
wire	SYNTHESIZED_WIRE_44;
wire	SYNTHESIZED_WIRE_45;
wire	SYNTHESIZED_WIRE_46;
wire	SYNTHESIZED_WIRE_52;
wire	SYNTHESIZED_WIRE_53;
wire	SYNTHESIZED_WIRE_54;
wire	SYNTHESIZED_WIRE_55;
wire	SYNTHESIZED_WIRE_60;
wire	SYNTHESIZED_WIRE_61;
wire	SYNTHESIZED_WIRE_62;
wire	SYNTHESIZED_WIRE_63;
wire	SYNTHESIZED_WIRE_69;
wire	SYNTHESIZED_WIRE_70;
wire	SYNTHESIZED_WIRE_71;
wire	SYNTHESIZED_WIRE_72;
wire	SYNTHESIZED_WIRE_77;
wire	SYNTHESIZED_WIRE_78;
wire	SYNTHESIZED_WIRE_79;
wire	SYNTHESIZED_WIRE_80;
wire	SYNTHESIZED_WIRE_86;
wire	SYNTHESIZED_WIRE_87;
wire	SYNTHESIZED_WIRE_88;
wire	SYNTHESIZED_WIRE_89;
wire	SYNTHESIZED_WIRE_94;
wire	SYNTHESIZED_WIRE_95;
wire	SYNTHESIZED_WIRE_96;
wire	SYNTHESIZED_WIRE_97;
wire	SYNTHESIZED_WIRE_103;
wire	SYNTHESIZED_WIRE_104;
wire	SYNTHESIZED_WIRE_105;
wire	SYNTHESIZED_WIRE_106;
wire	SYNTHESIZED_WIRE_111;
wire	SYNTHESIZED_WIRE_112;
wire	SYNTHESIZED_WIRE_113;
wire	SYNTHESIZED_WIRE_114;
wire	SYNTHESIZED_WIRE_117;
wire	SYNTHESIZED_WIRE_118;
wire	SYNTHESIZED_WIRE_119;
wire	SYNTHESIZED_WIRE_120;
wire	SYNTHESIZED_WIRE_123;
wire	SYNTHESIZED_WIRE_124;
wire	SYNTHESIZED_WIRE_125;
wire	SYNTHESIZED_WIRE_126;





\2to4Decoder 	b2v_inst(
	.DA(S),
	.m0(SYNTHESIZED_WIRE_130),
	.m1(SYNTHESIZED_WIRE_131),
	.m2(SYNTHESIZED_WIRE_128),
	.m3(SYNTHESIZED_WIRE_129));

assign	SYNTHESIZED_WIRE_3 = SYNTHESIZED_WIRE_128 & I2[1];

assign	SYNTHESIZED_WIRE_4 = SYNTHESIZED_WIRE_129 & I3[1];

assign	F_ALTERA_SYNTHESIZED[1] = SYNTHESIZED_WIRE_2 | SYNTHESIZED_WIRE_3 | SYNTHESIZED_WIRE_4 | SYNTHESIZED_WIRE_5;

assign	SYNTHESIZED_WIRE_10 = SYNTHESIZED_WIRE_130 & I0[2];

assign	SYNTHESIZED_WIRE_13 = SYNTHESIZED_WIRE_131 & I1[2];

assign	SYNTHESIZED_WIRE_11 = SYNTHESIZED_WIRE_128 & I2[2];

assign	SYNTHESIZED_WIRE_12 = SYNTHESIZED_WIRE_129 & I3[2];

assign	F_ALTERA_SYNTHESIZED[2] = SYNTHESIZED_WIRE_10 | SYNTHESIZED_WIRE_11 | SYNTHESIZED_WIRE_12 | SYNTHESIZED_WIRE_13;

assign	SYNTHESIZED_WIRE_18 = SYNTHESIZED_WIRE_130 & I0[3];

assign	SYNTHESIZED_WIRE_21 = SYNTHESIZED_WIRE_131 & I1[3];

assign	SYNTHESIZED_WIRE_19 = SYNTHESIZED_WIRE_128 & I2[3];

assign	SYNTHESIZED_WIRE_20 = SYNTHESIZED_WIRE_129 & I3[3];

assign	F_ALTERA_SYNTHESIZED[3] = SYNTHESIZED_WIRE_18 | SYNTHESIZED_WIRE_19 | SYNTHESIZED_WIRE_20 | SYNTHESIZED_WIRE_21;

assign	SYNTHESIZED_WIRE_26 = SYNTHESIZED_WIRE_130 & I0[4];

assign	SYNTHESIZED_WIRE_29 = SYNTHESIZED_WIRE_131 & I1[4];

assign	SYNTHESIZED_WIRE_27 = SYNTHESIZED_WIRE_128 & I2[4];

assign	SYNTHESIZED_WIRE_28 = SYNTHESIZED_WIRE_129 & I3[4];

assign	F_ALTERA_SYNTHESIZED[4] = SYNTHESIZED_WIRE_26 | SYNTHESIZED_WIRE_27 | SYNTHESIZED_WIRE_28 | SYNTHESIZED_WIRE_29;

assign	SYNTHESIZED_WIRE_35 = SYNTHESIZED_WIRE_130 & I0[5];

assign	SYNTHESIZED_WIRE_38 = SYNTHESIZED_WIRE_131 & I1[5];

assign	SYNTHESIZED_WIRE_117 = SYNTHESIZED_WIRE_130 & I0[0];

assign	SYNTHESIZED_WIRE_36 = SYNTHESIZED_WIRE_128 & I2[5];

assign	SYNTHESIZED_WIRE_37 = SYNTHESIZED_WIRE_129 & I3[5];

assign	F_ALTERA_SYNTHESIZED[5] = SYNTHESIZED_WIRE_35 | SYNTHESIZED_WIRE_36 | SYNTHESIZED_WIRE_37 | SYNTHESIZED_WIRE_38;

assign	SYNTHESIZED_WIRE_43 = SYNTHESIZED_WIRE_130 & I0[6];

assign	SYNTHESIZED_WIRE_46 = SYNTHESIZED_WIRE_131 & I1[6];

assign	SYNTHESIZED_WIRE_44 = SYNTHESIZED_WIRE_128 & I2[6];

assign	SYNTHESIZED_WIRE_45 = SYNTHESIZED_WIRE_129 & I3[6];

assign	F_ALTERA_SYNTHESIZED[6] = SYNTHESIZED_WIRE_43 | SYNTHESIZED_WIRE_44 | SYNTHESIZED_WIRE_45 | SYNTHESIZED_WIRE_46;

assign	SYNTHESIZED_WIRE_52 = SYNTHESIZED_WIRE_130 & I0[7];

assign	SYNTHESIZED_WIRE_55 = SYNTHESIZED_WIRE_131 & I1[7];

assign	SYNTHESIZED_WIRE_120 = SYNTHESIZED_WIRE_131 & I1[0];

assign	SYNTHESIZED_WIRE_53 = SYNTHESIZED_WIRE_128 & I2[7];

assign	SYNTHESIZED_WIRE_54 = SYNTHESIZED_WIRE_129 & I3[7];

assign	F_ALTERA_SYNTHESIZED[7] = SYNTHESIZED_WIRE_52 | SYNTHESIZED_WIRE_53 | SYNTHESIZED_WIRE_54 | SYNTHESIZED_WIRE_55;

assign	SYNTHESIZED_WIRE_60 = SYNTHESIZED_WIRE_130 & I0[8];

assign	SYNTHESIZED_WIRE_63 = SYNTHESIZED_WIRE_131 & I1[8];

assign	SYNTHESIZED_WIRE_61 = SYNTHESIZED_WIRE_128 & I2[8];

assign	SYNTHESIZED_WIRE_62 = SYNTHESIZED_WIRE_129 & I3[8];

assign	F_ALTERA_SYNTHESIZED[8] = SYNTHESIZED_WIRE_60 | SYNTHESIZED_WIRE_61 | SYNTHESIZED_WIRE_62 | SYNTHESIZED_WIRE_63;

assign	SYNTHESIZED_WIRE_69 = SYNTHESIZED_WIRE_130 & I0[9];

assign	SYNTHESIZED_WIRE_72 = SYNTHESIZED_WIRE_131 & I1[9];

assign	SYNTHESIZED_WIRE_118 = SYNTHESIZED_WIRE_128 & I2[0];

assign	SYNTHESIZED_WIRE_70 = SYNTHESIZED_WIRE_128 & I2[9];

assign	SYNTHESIZED_WIRE_71 = SYNTHESIZED_WIRE_129 & I3[9];

assign	F_ALTERA_SYNTHESIZED[9] = SYNTHESIZED_WIRE_69 | SYNTHESIZED_WIRE_70 | SYNTHESIZED_WIRE_71 | SYNTHESIZED_WIRE_72;

assign	SYNTHESIZED_WIRE_77 = SYNTHESIZED_WIRE_130 & I0[10];

assign	SYNTHESIZED_WIRE_80 = SYNTHESIZED_WIRE_131 & I1[10];

assign	SYNTHESIZED_WIRE_78 = SYNTHESIZED_WIRE_128 & I2[10];

assign	SYNTHESIZED_WIRE_79 = SYNTHESIZED_WIRE_129 & I3[10];

assign	F_ALTERA_SYNTHESIZED[10] = SYNTHESIZED_WIRE_77 | SYNTHESIZED_WIRE_78 | SYNTHESIZED_WIRE_79 | SYNTHESIZED_WIRE_80;

assign	SYNTHESIZED_WIRE_86 = SYNTHESIZED_WIRE_130 & I0[11];

assign	SYNTHESIZED_WIRE_89 = SYNTHESIZED_WIRE_131 & I1[11];

assign	SYNTHESIZED_WIRE_119 = SYNTHESIZED_WIRE_129 & I3[0];

assign	SYNTHESIZED_WIRE_87 = SYNTHESIZED_WIRE_128 & I2[11];

assign	SYNTHESIZED_WIRE_88 = SYNTHESIZED_WIRE_129 & I3[11];

assign	F_ALTERA_SYNTHESIZED[11] = SYNTHESIZED_WIRE_86 | SYNTHESIZED_WIRE_87 | SYNTHESIZED_WIRE_88 | SYNTHESIZED_WIRE_89;

assign	SYNTHESIZED_WIRE_94 = SYNTHESIZED_WIRE_130 & I0[12];

assign	SYNTHESIZED_WIRE_97 = SYNTHESIZED_WIRE_131 & I1[12];

assign	SYNTHESIZED_WIRE_95 = SYNTHESIZED_WIRE_128 & I2[12];

assign	SYNTHESIZED_WIRE_96 = SYNTHESIZED_WIRE_129 & I3[12];

assign	F_ALTERA_SYNTHESIZED[12] = SYNTHESIZED_WIRE_94 | SYNTHESIZED_WIRE_95 | SYNTHESIZED_WIRE_96 | SYNTHESIZED_WIRE_97;

assign	SYNTHESIZED_WIRE_103 = SYNTHESIZED_WIRE_130 & I0[13];

assign	SYNTHESIZED_WIRE_106 = SYNTHESIZED_WIRE_131 & I1[13];

assign	SYNTHESIZED_WIRE_2 = SYNTHESIZED_WIRE_130 & I0[1];

assign	SYNTHESIZED_WIRE_104 = SYNTHESIZED_WIRE_128 & I2[13];

assign	SYNTHESIZED_WIRE_105 = SYNTHESIZED_WIRE_129 & I3[13];

assign	F_ALTERA_SYNTHESIZED[13] = SYNTHESIZED_WIRE_103 | SYNTHESIZED_WIRE_104 | SYNTHESIZED_WIRE_105 | SYNTHESIZED_WIRE_106;

assign	SYNTHESIZED_WIRE_111 = SYNTHESIZED_WIRE_130 & I0[14];

assign	SYNTHESIZED_WIRE_114 = SYNTHESIZED_WIRE_131 & I1[14];

assign	SYNTHESIZED_WIRE_112 = SYNTHESIZED_WIRE_128 & I2[14];

assign	SYNTHESIZED_WIRE_113 = SYNTHESIZED_WIRE_129 & I3[14];

assign	F_ALTERA_SYNTHESIZED[14] = SYNTHESIZED_WIRE_111 | SYNTHESIZED_WIRE_112 | SYNTHESIZED_WIRE_113 | SYNTHESIZED_WIRE_114;

assign	SYNTHESIZED_WIRE_123 = SYNTHESIZED_WIRE_130 & I0[15];

assign	SYNTHESIZED_WIRE_126 = SYNTHESIZED_WIRE_131 & I1[15];

assign	F_ALTERA_SYNTHESIZED[0] = SYNTHESIZED_WIRE_117 | SYNTHESIZED_WIRE_118 | SYNTHESIZED_WIRE_119 | SYNTHESIZED_WIRE_120;

assign	SYNTHESIZED_WIRE_124 = SYNTHESIZED_WIRE_128 & I2[15];

assign	SYNTHESIZED_WIRE_125 = SYNTHESIZED_WIRE_129 & I3[15];

assign	F_ALTERA_SYNTHESIZED[15] = SYNTHESIZED_WIRE_123 | SYNTHESIZED_WIRE_124 | SYNTHESIZED_WIRE_125 | SYNTHESIZED_WIRE_126;

assign	SYNTHESIZED_WIRE_5 = SYNTHESIZED_WIRE_131 & I1[1];

assign	F = F_ALTERA_SYNTHESIZED;

endmodule
