// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.

// PROGRAM		"Quartus II 64-Bit"
// VERSION		"Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition"
// CREATED		"Tue Mar 07 00:52:31 2017"

module \4by16LogicMux (
	I3,
	I2,
	I1,
	I0,
	A,
	B,
	F
);


input wire	I3;
input wire	I2;
input wire	I1;
input wire	I0;
input wire	[15:0] A;
input wire	[15:0] B;
output wire	[15:0] F;

wire	[15:0] F_ALTERA_SYNTHESIZED;
wire	SYNTHESIZED_WIRE_0;
wire	SYNTHESIZED_WIRE_1;
wire	SYNTHESIZED_WIRE_2;
wire	SYNTHESIZED_WIRE_3;
wire	SYNTHESIZED_WIRE_4;
wire	SYNTHESIZED_WIRE_5;
wire	SYNTHESIZED_WIRE_6;
wire	SYNTHESIZED_WIRE_7;
wire	SYNTHESIZED_WIRE_8;
wire	SYNTHESIZED_WIRE_9;
wire	SYNTHESIZED_WIRE_10;
wire	SYNTHESIZED_WIRE_11;
wire	SYNTHESIZED_WIRE_12;
wire	SYNTHESIZED_WIRE_13;
wire	SYNTHESIZED_WIRE_14;
wire	SYNTHESIZED_WIRE_15;
wire	SYNTHESIZED_WIRE_16;
wire	SYNTHESIZED_WIRE_17;
wire	SYNTHESIZED_WIRE_18;
wire	SYNTHESIZED_WIRE_19;
wire	SYNTHESIZED_WIRE_20;
wire	SYNTHESIZED_WIRE_21;
wire	SYNTHESIZED_WIRE_22;
wire	SYNTHESIZED_WIRE_23;
wire	SYNTHESIZED_WIRE_24;
wire	SYNTHESIZED_WIRE_25;
wire	SYNTHESIZED_WIRE_26;
wire	SYNTHESIZED_WIRE_27;
wire	SYNTHESIZED_WIRE_28;
wire	SYNTHESIZED_WIRE_29;
wire	SYNTHESIZED_WIRE_30;
wire	SYNTHESIZED_WIRE_31;
wire	SYNTHESIZED_WIRE_32;
wire	SYNTHESIZED_WIRE_33;
wire	SYNTHESIZED_WIRE_34;
wire	SYNTHESIZED_WIRE_35;
wire	SYNTHESIZED_WIRE_36;
wire	SYNTHESIZED_WIRE_37;
wire	SYNTHESIZED_WIRE_38;
wire	SYNTHESIZED_WIRE_39;
wire	SYNTHESIZED_WIRE_40;
wire	SYNTHESIZED_WIRE_41;
wire	SYNTHESIZED_WIRE_42;
wire	SYNTHESIZED_WIRE_43;
wire	SYNTHESIZED_WIRE_44;
wire	SYNTHESIZED_WIRE_45;
wire	SYNTHESIZED_WIRE_46;
wire	SYNTHESIZED_WIRE_47;
wire	SYNTHESIZED_WIRE_48;
wire	SYNTHESIZED_WIRE_49;
wire	SYNTHESIZED_WIRE_50;
wire	SYNTHESIZED_WIRE_51;
wire	SYNTHESIZED_WIRE_52;
wire	SYNTHESIZED_WIRE_53;
wire	SYNTHESIZED_WIRE_54;
wire	SYNTHESIZED_WIRE_55;
wire	SYNTHESIZED_WIRE_56;
wire	SYNTHESIZED_WIRE_57;
wire	SYNTHESIZED_WIRE_58;
wire	SYNTHESIZED_WIRE_59;
wire	SYNTHESIZED_WIRE_60;
wire	SYNTHESIZED_WIRE_61;
wire	SYNTHESIZED_WIRE_62;
wire	SYNTHESIZED_WIRE_63;
wire	SYNTHESIZED_WIRE_64;
wire	SYNTHESIZED_WIRE_65;
wire	SYNTHESIZED_WIRE_66;
wire	SYNTHESIZED_WIRE_67;
wire	SYNTHESIZED_WIRE_68;
wire	SYNTHESIZED_WIRE_69;
wire	SYNTHESIZED_WIRE_70;
wire	SYNTHESIZED_WIRE_71;
wire	SYNTHESIZED_WIRE_72;
wire	SYNTHESIZED_WIRE_73;
wire	SYNTHESIZED_WIRE_74;
wire	SYNTHESIZED_WIRE_75;
wire	SYNTHESIZED_WIRE_76;
wire	SYNTHESIZED_WIRE_77;
wire	SYNTHESIZED_WIRE_78;
wire	SYNTHESIZED_WIRE_79;
wire	SYNTHESIZED_WIRE_80;
wire	SYNTHESIZED_WIRE_81;
wire	SYNTHESIZED_WIRE_82;
wire	SYNTHESIZED_WIRE_83;
wire	SYNTHESIZED_WIRE_84;
wire	SYNTHESIZED_WIRE_85;
wire	SYNTHESIZED_WIRE_86;
wire	SYNTHESIZED_WIRE_87;
wire	SYNTHESIZED_WIRE_88;
wire	SYNTHESIZED_WIRE_89;
wire	SYNTHESIZED_WIRE_90;
wire	SYNTHESIZED_WIRE_91;
wire	SYNTHESIZED_WIRE_92;
wire	SYNTHESIZED_WIRE_93;
wire	SYNTHESIZED_WIRE_94;
wire	SYNTHESIZED_WIRE_95;
wire	SYNTHESIZED_WIRE_96;
wire	SYNTHESIZED_WIRE_97;
wire	SYNTHESIZED_WIRE_98;
wire	SYNTHESIZED_WIRE_99;
wire	SYNTHESIZED_WIRE_100;
wire	SYNTHESIZED_WIRE_101;
wire	SYNTHESIZED_WIRE_102;
wire	SYNTHESIZED_WIRE_103;
wire	SYNTHESIZED_WIRE_104;
wire	SYNTHESIZED_WIRE_105;
wire	SYNTHESIZED_WIRE_106;
wire	SYNTHESIZED_WIRE_107;
wire	SYNTHESIZED_WIRE_108;
wire	SYNTHESIZED_WIRE_109;
wire	SYNTHESIZED_WIRE_110;
wire	SYNTHESIZED_WIRE_111;
wire	SYNTHESIZED_WIRE_112;
wire	SYNTHESIZED_WIRE_113;
wire	SYNTHESIZED_WIRE_114;
wire	SYNTHESIZED_WIRE_115;
wire	SYNTHESIZED_WIRE_116;
wire	SYNTHESIZED_WIRE_117;
wire	SYNTHESIZED_WIRE_118;
wire	SYNTHESIZED_WIRE_119;
wire	SYNTHESIZED_WIRE_120;
wire	SYNTHESIZED_WIRE_121;
wire	SYNTHESIZED_WIRE_122;
wire	SYNTHESIZED_WIRE_123;
wire	SYNTHESIZED_WIRE_124;
wire	SYNTHESIZED_WIRE_125;
wire	SYNTHESIZED_WIRE_126;
wire	SYNTHESIZED_WIRE_127;





\2to4Decoder_2Inputs 	b2v_inst(
	.A(A[0]),
	.B(B[0]),
	.m0(SYNTHESIZED_WIRE_18),
	.m1(SYNTHESIZED_WIRE_34),
	.m2(SYNTHESIZED_WIRE_46),
	.m3(SYNTHESIZED_WIRE_61));

assign	F_ALTERA_SYNTHESIZED[0] = SYNTHESIZED_WIRE_0 | SYNTHESIZED_WIRE_1 | SYNTHESIZED_WIRE_2 | SYNTHESIZED_WIRE_3;

assign	SYNTHESIZED_WIRE_7 = I3 & SYNTHESIZED_WIRE_4;

assign	F_ALTERA_SYNTHESIZED[1] = SYNTHESIZED_WIRE_5 | SYNTHESIZED_WIRE_6 | SYNTHESIZED_WIRE_7 | SYNTHESIZED_WIRE_8;


\2to4Decoder_2Inputs 	b2v_inst12(
	.A(A[2]),
	.B(B[2]),
	.m0(SYNTHESIZED_WIRE_9),
	.m1(SYNTHESIZED_WIRE_10),
	.m2(SYNTHESIZED_WIRE_11),
	.m3(SYNTHESIZED_WIRE_12));

assign	SYNTHESIZED_WIRE_13 = I0 & SYNTHESIZED_WIRE_9;

assign	SYNTHESIZED_WIRE_16 = I1 & SYNTHESIZED_WIRE_10;

assign	SYNTHESIZED_WIRE_14 = I2 & SYNTHESIZED_WIRE_11;

assign	SYNTHESIZED_WIRE_15 = I3 & SYNTHESIZED_WIRE_12;

assign	F_ALTERA_SYNTHESIZED[2] = SYNTHESIZED_WIRE_13 | SYNTHESIZED_WIRE_14 | SYNTHESIZED_WIRE_15 | SYNTHESIZED_WIRE_16;


\2to4Decoder_2Inputs 	b2v_inst18(
	.A(A[3]),
	.B(B[3]),
	.m0(SYNTHESIZED_WIRE_17),
	.m1(SYNTHESIZED_WIRE_19),
	.m2(SYNTHESIZED_WIRE_20),
	.m3(SYNTHESIZED_WIRE_21));

assign	SYNTHESIZED_WIRE_22 = I0 & SYNTHESIZED_WIRE_17;

assign	SYNTHESIZED_WIRE_0 = I0 & SYNTHESIZED_WIRE_18;

assign	SYNTHESIZED_WIRE_25 = I1 & SYNTHESIZED_WIRE_19;

assign	SYNTHESIZED_WIRE_23 = I2 & SYNTHESIZED_WIRE_20;

assign	SYNTHESIZED_WIRE_24 = I3 & SYNTHESIZED_WIRE_21;

assign	F_ALTERA_SYNTHESIZED[3] = SYNTHESIZED_WIRE_22 | SYNTHESIZED_WIRE_23 | SYNTHESIZED_WIRE_24 | SYNTHESIZED_WIRE_25;


\2to4Decoder_2Inputs 	b2v_inst24(
	.A(A[4]),
	.B(B[4]),
	.m0(SYNTHESIZED_WIRE_26),
	.m1(SYNTHESIZED_WIRE_27),
	.m2(SYNTHESIZED_WIRE_28),
	.m3(SYNTHESIZED_WIRE_29));

assign	SYNTHESIZED_WIRE_30 = I0 & SYNTHESIZED_WIRE_26;

assign	SYNTHESIZED_WIRE_33 = I1 & SYNTHESIZED_WIRE_27;

assign	SYNTHESIZED_WIRE_31 = I2 & SYNTHESIZED_WIRE_28;

assign	SYNTHESIZED_WIRE_32 = I3 & SYNTHESIZED_WIRE_29;

assign	F_ALTERA_SYNTHESIZED[4] = SYNTHESIZED_WIRE_30 | SYNTHESIZED_WIRE_31 | SYNTHESIZED_WIRE_32 | SYNTHESIZED_WIRE_33;

assign	SYNTHESIZED_WIRE_3 = I1 & SYNTHESIZED_WIRE_34;


\2to4Decoder_2Inputs 	b2v_inst30(
	.A(A[5]),
	.B(B[5]),
	.m0(SYNTHESIZED_WIRE_35),
	.m1(SYNTHESIZED_WIRE_36),
	.m2(SYNTHESIZED_WIRE_37),
	.m3(SYNTHESIZED_WIRE_38));

assign	SYNTHESIZED_WIRE_39 = I0 & SYNTHESIZED_WIRE_35;

assign	SYNTHESIZED_WIRE_42 = I1 & SYNTHESIZED_WIRE_36;

assign	SYNTHESIZED_WIRE_40 = I2 & SYNTHESIZED_WIRE_37;

assign	SYNTHESIZED_WIRE_41 = I3 & SYNTHESIZED_WIRE_38;

assign	F_ALTERA_SYNTHESIZED[5] = SYNTHESIZED_WIRE_39 | SYNTHESIZED_WIRE_40 | SYNTHESIZED_WIRE_41 | SYNTHESIZED_WIRE_42;


\2to4Decoder_2Inputs 	b2v_inst36(
	.A(A[6]),
	.B(B[6]),
	.m0(SYNTHESIZED_WIRE_43),
	.m1(SYNTHESIZED_WIRE_44),
	.m2(SYNTHESIZED_WIRE_45),
	.m3(SYNTHESIZED_WIRE_47));

assign	SYNTHESIZED_WIRE_48 = I0 & SYNTHESIZED_WIRE_43;

assign	SYNTHESIZED_WIRE_51 = I1 & SYNTHESIZED_WIRE_44;

assign	SYNTHESIZED_WIRE_49 = I2 & SYNTHESIZED_WIRE_45;

assign	SYNTHESIZED_WIRE_1 = I2 & SYNTHESIZED_WIRE_46;

assign	SYNTHESIZED_WIRE_50 = I3 & SYNTHESIZED_WIRE_47;

assign	F_ALTERA_SYNTHESIZED[6] = SYNTHESIZED_WIRE_48 | SYNTHESIZED_WIRE_49 | SYNTHESIZED_WIRE_50 | SYNTHESIZED_WIRE_51;


\2to4Decoder_2Inputs 	b2v_inst42(
	.A(A[7]),
	.B(B[7]),
	.m0(SYNTHESIZED_WIRE_52),
	.m1(SYNTHESIZED_WIRE_53),
	.m2(SYNTHESIZED_WIRE_54),
	.m3(SYNTHESIZED_WIRE_55));

assign	SYNTHESIZED_WIRE_56 = I0 & SYNTHESIZED_WIRE_52;

assign	SYNTHESIZED_WIRE_59 = I1 & SYNTHESIZED_WIRE_53;

assign	SYNTHESIZED_WIRE_57 = I2 & SYNTHESIZED_WIRE_54;

assign	SYNTHESIZED_WIRE_58 = I3 & SYNTHESIZED_WIRE_55;

assign	F_ALTERA_SYNTHESIZED[7] = SYNTHESIZED_WIRE_56 | SYNTHESIZED_WIRE_57 | SYNTHESIZED_WIRE_58 | SYNTHESIZED_WIRE_59;


\2to4Decoder_2Inputs 	b2v_inst48(
	.A(A[8]),
	.B(B[8]),
	.m0(SYNTHESIZED_WIRE_60),
	.m1(SYNTHESIZED_WIRE_62),
	.m2(SYNTHESIZED_WIRE_63),
	.m3(SYNTHESIZED_WIRE_64));

assign	SYNTHESIZED_WIRE_65 = I0 & SYNTHESIZED_WIRE_60;

assign	SYNTHESIZED_WIRE_2 = I3 & SYNTHESIZED_WIRE_61;

assign	SYNTHESIZED_WIRE_68 = I1 & SYNTHESIZED_WIRE_62;

assign	SYNTHESIZED_WIRE_66 = I2 & SYNTHESIZED_WIRE_63;

assign	SYNTHESIZED_WIRE_67 = I3 & SYNTHESIZED_WIRE_64;

assign	F_ALTERA_SYNTHESIZED[8] = SYNTHESIZED_WIRE_65 | SYNTHESIZED_WIRE_66 | SYNTHESIZED_WIRE_67 | SYNTHESIZED_WIRE_68;


\2to4Decoder_2Inputs 	b2v_inst54(
	.A(A[9]),
	.B(B[9]),
	.m0(SYNTHESIZED_WIRE_69),
	.m1(SYNTHESIZED_WIRE_70),
	.m2(SYNTHESIZED_WIRE_71),
	.m3(SYNTHESIZED_WIRE_72));

assign	SYNTHESIZED_WIRE_73 = I0 & SYNTHESIZED_WIRE_69;

assign	SYNTHESIZED_WIRE_76 = I1 & SYNTHESIZED_WIRE_70;

assign	SYNTHESIZED_WIRE_74 = I2 & SYNTHESIZED_WIRE_71;

assign	SYNTHESIZED_WIRE_75 = I3 & SYNTHESIZED_WIRE_72;

assign	F_ALTERA_SYNTHESIZED[9] = SYNTHESIZED_WIRE_73 | SYNTHESIZED_WIRE_74 | SYNTHESIZED_WIRE_75 | SYNTHESIZED_WIRE_76;


\2to4Decoder_2Inputs 	b2v_inst6(
	.A(A[1]),
	.B(B[1]),
	.m0(SYNTHESIZED_WIRE_88),
	.m1(SYNTHESIZED_WIRE_103),
	.m2(SYNTHESIZED_WIRE_119),
	.m3(SYNTHESIZED_WIRE_4));


\2to4Decoder_2Inputs 	b2v_inst60(
	.A(A[10]),
	.B(B[10]),
	.m0(SYNTHESIZED_WIRE_77),
	.m1(SYNTHESIZED_WIRE_78),
	.m2(SYNTHESIZED_WIRE_79),
	.m3(SYNTHESIZED_WIRE_80));

assign	SYNTHESIZED_WIRE_81 = I0 & SYNTHESIZED_WIRE_77;

assign	SYNTHESIZED_WIRE_84 = I1 & SYNTHESIZED_WIRE_78;

assign	SYNTHESIZED_WIRE_82 = I2 & SYNTHESIZED_WIRE_79;

assign	SYNTHESIZED_WIRE_83 = I3 & SYNTHESIZED_WIRE_80;

assign	F_ALTERA_SYNTHESIZED[10] = SYNTHESIZED_WIRE_81 | SYNTHESIZED_WIRE_82 | SYNTHESIZED_WIRE_83 | SYNTHESIZED_WIRE_84;


\2to4Decoder_2Inputs 	b2v_inst66(
	.A(A[11]),
	.B(B[11]),
	.m0(SYNTHESIZED_WIRE_85),
	.m1(SYNTHESIZED_WIRE_86),
	.m2(SYNTHESIZED_WIRE_87),
	.m3(SYNTHESIZED_WIRE_89));

assign	SYNTHESIZED_WIRE_90 = I0 & SYNTHESIZED_WIRE_85;

assign	SYNTHESIZED_WIRE_93 = I1 & SYNTHESIZED_WIRE_86;

assign	SYNTHESIZED_WIRE_91 = I2 & SYNTHESIZED_WIRE_87;

assign	SYNTHESIZED_WIRE_5 = I0 & SYNTHESIZED_WIRE_88;

assign	SYNTHESIZED_WIRE_92 = I3 & SYNTHESIZED_WIRE_89;

assign	F_ALTERA_SYNTHESIZED[11] = SYNTHESIZED_WIRE_90 | SYNTHESIZED_WIRE_91 | SYNTHESIZED_WIRE_92 | SYNTHESIZED_WIRE_93;


\2to4Decoder_2Inputs 	b2v_inst72(
	.A(A[12]),
	.B(B[12]),
	.m0(SYNTHESIZED_WIRE_94),
	.m1(SYNTHESIZED_WIRE_95),
	.m2(SYNTHESIZED_WIRE_96),
	.m3(SYNTHESIZED_WIRE_97));

assign	SYNTHESIZED_WIRE_98 = I0 & SYNTHESIZED_WIRE_94;

assign	SYNTHESIZED_WIRE_101 = I1 & SYNTHESIZED_WIRE_95;

assign	SYNTHESIZED_WIRE_99 = I2 & SYNTHESIZED_WIRE_96;

assign	SYNTHESIZED_WIRE_100 = I3 & SYNTHESIZED_WIRE_97;

assign	F_ALTERA_SYNTHESIZED[12] = SYNTHESIZED_WIRE_98 | SYNTHESIZED_WIRE_99 | SYNTHESIZED_WIRE_100 | SYNTHESIZED_WIRE_101;


\2to4Decoder_2Inputs 	b2v_inst78(
	.A(A[13]),
	.B(B[13]),
	.m0(SYNTHESIZED_WIRE_102),
	.m1(SYNTHESIZED_WIRE_104),
	.m2(SYNTHESIZED_WIRE_105),
	.m3(SYNTHESIZED_WIRE_106));

assign	SYNTHESIZED_WIRE_107 = I0 & SYNTHESIZED_WIRE_102;

assign	SYNTHESIZED_WIRE_8 = I1 & SYNTHESIZED_WIRE_103;

assign	SYNTHESIZED_WIRE_110 = I1 & SYNTHESIZED_WIRE_104;

assign	SYNTHESIZED_WIRE_108 = I2 & SYNTHESIZED_WIRE_105;

assign	SYNTHESIZED_WIRE_109 = I3 & SYNTHESIZED_WIRE_106;

assign	F_ALTERA_SYNTHESIZED[13] = SYNTHESIZED_WIRE_107 | SYNTHESIZED_WIRE_108 | SYNTHESIZED_WIRE_109 | SYNTHESIZED_WIRE_110;


\2to4Decoder_2Inputs 	b2v_inst84(
	.A(A[14]),
	.B(B[14]),
	.m0(SYNTHESIZED_WIRE_111),
	.m1(SYNTHESIZED_WIRE_112),
	.m2(SYNTHESIZED_WIRE_113),
	.m3(SYNTHESIZED_WIRE_114));

assign	SYNTHESIZED_WIRE_115 = I0 & SYNTHESIZED_WIRE_111;

assign	SYNTHESIZED_WIRE_118 = I1 & SYNTHESIZED_WIRE_112;

assign	SYNTHESIZED_WIRE_116 = I2 & SYNTHESIZED_WIRE_113;

assign	SYNTHESIZED_WIRE_117 = I3 & SYNTHESIZED_WIRE_114;

assign	F_ALTERA_SYNTHESIZED[14] = SYNTHESIZED_WIRE_115 | SYNTHESIZED_WIRE_116 | SYNTHESIZED_WIRE_117 | SYNTHESIZED_WIRE_118;

assign	SYNTHESIZED_WIRE_6 = I2 & SYNTHESIZED_WIRE_119;


\2to4Decoder_2Inputs 	b2v_inst90(
	.A(A[15]),
	.B(B[15]),
	.m0(SYNTHESIZED_WIRE_120),
	.m1(SYNTHESIZED_WIRE_121),
	.m2(SYNTHESIZED_WIRE_122),
	.m3(SYNTHESIZED_WIRE_123));

assign	SYNTHESIZED_WIRE_124 = I0 & SYNTHESIZED_WIRE_120;

assign	SYNTHESIZED_WIRE_127 = I1 & SYNTHESIZED_WIRE_121;

assign	SYNTHESIZED_WIRE_125 = I2 & SYNTHESIZED_WIRE_122;

assign	SYNTHESIZED_WIRE_126 = I3 & SYNTHESIZED_WIRE_123;

assign	F_ALTERA_SYNTHESIZED[15] = SYNTHESIZED_WIRE_124 | SYNTHESIZED_WIRE_125 | SYNTHESIZED_WIRE_126 | SYNTHESIZED_WIRE_127;

assign	F = F_ALTERA_SYNTHESIZED;

endmodule
